### PR TITLE
fix: Typo httpLoggingExludePaths to httpLoggingExcludePaths

### PR DESCRIPTION
**Pull request by jmunozherbas**
- Target issue #
https://github.com/JanssenProject/jans/issues/1085

-----------------------------
- Implementation Details
Fix typo "httpLoggingExludePaths" in different places:

jans-auth-server 
jans-cli 
jans-config-api 
jans-linux-setup 
docker-jans-persistence-loader

-----------------------------
### Document changes
"httpLoggingExludePaths" was changed to "httpLoggingExcludePaths" in next documents and config files:

https://github.com/JanssenProject/jans/blob/main/docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.json
https://github.com/JanssenProject/jans/blob/main/docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.ob.json
https://github.com/JanssenProject/jans/blob/main/jans-cli/cli/jca.yaml
https://github.com/JanssenProject/jans/blob/main/jans-cli/docs/cli/cli-jans-authorization-server.md
https://github.com/JanssenProject/jans/blob/main/jans-cli/docs/cli/cli-logging-configuration.md
https://github.com/JanssenProject/jans/blob/main/jans-cli/docs/im/im-jans-authorization-server.md
https://github.com/JanssenProject/jans/blob/main/jans-cli/docs/im/im-janssen-logging-configuration.md
https://github.com/JanssenProject/jans/blob/main/jans-config-api/docs/jans-config-api-swagger.yaml
https://github.com/JanssenProject/jans/blob/main/jans-linux-setup/jans_setup/openbanking/templates/jans-auth/jans-auth-config.json
https://github.com/JanssenProject/jans/blob/main/jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-config.json

### CODE REVIEW

**Review by Milton-Ch — APPROVED** [review]
LGTM, just one note, every one who is using this config currently might get affected, I'd suggest to communicate this change when it gets merged.

**Comment by yuriyz** [comment]
@jmunozherbas Looks like its ready for review and merge, however still as draft. Should it be marked as "Ready for review"?

**Comment by jmunozherbas** [comment]
> @jmunozherbas Looks like its ready for review and merge, however still as draft. Should it be marked as "Ready for review"?

Yes, the PR is ready, I was waiting for Jenkins Build.

**Review by moabu — APPROVED** [review]

**Comment by yuriyz** [comment]
Who else should approve this PR ? @iromli @mbaser

**Review by iromli — APPROVED** [review]

**Review by mbaser — APPROVED** [review]

**Pull request merged**
