### PR TITLE
feat(jans-cedarling): update Trusted Issuers schema in the policy store

### LINKED ISSUE #10038: fix(cedarling): Make cedarling Policy Store compatible with Agama Lab
We need to make trusted store compatible with agama-lab. See [Wiki](https://github.com/JanssenProject/jans/wiki/Cedarling-Nativity-Plan#cedarling-policy-store) for final design.

### PR DESCRIPTION
**Pull request by rmarinn**
### Prepare

- [x] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [x] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

### Description

This PR updates the parser to handle the new *Trusted Issuers* and *Token Entity Metadata* schemas.

#### Target issue

The issue addressed by this PR involves users being unable to directly use policy stores exported from Agama Lab's Policy Designer.

closes #10038

#### Updated Trusted Issuers Schema

```json
"trusted_issuers": {
  "some_unique_id" : {
    "name": "name_of_the_trusted_issuer",
    "description": "description for the trusted issuer",
    "openid_configuration_endpoint": "https://<trusted-issuer-hostname>/.well-known/openid-configuration",
    "access_tokens": { 
      "trusted": true,
      "principlal_identifier": "jti",
      ...
    },
    "id_tokens": { ... },
    "userinfo_tokens": { ... },
    "tx_tokens": { ... },
  },
  ...
}
```

#### Updated Token Entity Metadata schema (used for: access_tokens, id_tokens, usrinfo_tokens, and tx_tokens).

```json
{
  "token_type": {
    "user_id": "<field name in token (e.g., 'email', 'sub', 'uid', etc.) or '' if not used>",
    "role_mapping": "<field for role assignment (e.g., 'role', 'memberOf', etc.) or '' if not used>",
    "claim_mapping": {
      "mapping_target": {
        "parser": "<type of parser ('regex' or 'json')>",
        "type": "<type identifier (e.g., 'Acme::Email')>",
        "...": "Additional configurations specific to the parser"
      },
    },
  }
}
```

-------------------
### Test and Document the changes
- [x] Static code analysis has been run locally and issues have been fixed
- [x] Relevant unit and integration tests have been added/updated
- [x] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

Please check the below before submitting your PR. The PR will not be merged if there are no commits that start with `docs:` to indicate documentation changes or if the below checklist is not selected.
- [ ] **I confirm that there is no impact on the docs due to the code changes in this PR.**

### CODE REVIEW

**Review by duttarnab — CHANGES_REQUESTED** [review]
Looks good to me. We need to ensure all test cases run with the Trusted Issuers schema changes.

**Review by duttarnab — DISMISSED** [review]

**Review by djellemah — COMMENTED** [review]
Looks fine to me.

My only question is this: will the `identity_source` to `trusted_issuers` rename prevent the import of a policy file exported by Policy Designer?

If so, will Policy Designer export be updated?

**Comment by olehbozhok** [comment]
> Looks fine to me.
> 
> My only question is this: will the `identity_source` to `trusted_issuers` rename prevent the import of a policy file exported by Policy Designer?
> 
> If so, will Policy Designer export be updated?

update was make to support last structure in the [wiki](https://github.com/JanssenProject/jans/wiki/Cedarling-Nativity-Plan#cedarling-policy-store)

**Review by olehbozhok — APPROVED** [review]
Looks OK to me

**Pull request merged**
