### PR TITLE
fix(jans-auth): Issue 3088 - "One step" authentication flow using Super Gluu

### PR DESCRIPTION
**Pull request by maduvena**
#3088

### CODE REVIEW

**Review by yuriyz — CHANGES_REQUESTED** [review]
In jans fido is seperate project. Thus I vote to keep these changes in https://github.com/JanssenProject/jans/tree/main/jans-fido2

**Comment by yurem** [comment]
> In jans fido is seperate project. Thus I vote to keep these changes in https://github.com/JanssenProject/jans/tree/main/jans-fido2

I agree with this. Also I wonder if we really need this old code in Jans. It's our first version which support U2F (v1) only. Now Fido2 server supports both U2F and Fido2. @maduvena I think we need to apply our custom U2F parts to Fido2 server code. Our long target is to move Super Gluu to use Fido2 server. This update will be steep in this direction.

**Comment by nynymike** [comment]
We want to remove FIDO U2F endpoints from Auth Server... the idea was to move U2F to the FIDO server...

**Review by yuriyz — APPROVED** [review]
For jans-auth-server looks good. We need Yura to review fido2 changes part.

**Pull request closed without merging**
