### PR TITLE
feat: add script for Google login

### PR DESCRIPTION
**Pull request by maduvena**
### Prepare

- [ ] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [ ] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

#### Implementation Details
  

-------------------
### Test and Document the changes
- [ ] Static code analysis has been run locally and issues have been fixed
- [ ] Relevant unit and integration tests have been added/updated
- [ ] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

### CODE REVIEW

**Review by yuriyz — DISMISSED** [review]

**Comment by moabu** [comment]
Yes we agreed on putting it in jans-linux-setup as the central place

**Comment by yuriyz** [comment]
@maduvena please move these resources to setup.

**Review by jgomer2001 — CHANGES_REQUESTED** [review]
There is usage of "ox..." attributes (inexisting in Jans)
There is mention of SMS in the instructions

**Review by jgomer2001 — APPROVED** [review]

**Review by mbaser — APPROVED** [review]
This part 
https://github.com/JanssenProject/jans/pull/1141/commits/b0ce3d439a756c586667dcbda56fc890805e642b#diff-5a1a282adaaec3b71da4b8c588a2e668616106d2f9100c446ec59690f119292cR44-R56

can be modified as  follows:

```
with open(google_creds_file, 'r') as f:
    try:
        data = json.loads(f.read())
        print data
        creds = data["web"]
        print creds
    except:
        print "Google. Initialization. Failed to load creds from file:", google_creds_file
        print "Exception: ", sys.exc_info()[1]

        return False
       ```

**Review by yurem — APPROVED** [review]

**Pull request merged**
