### PR TITLE
build: sync scan_update_token script #1820

### LINKED ISSUE #1820: feat: load update token script in persistence
Load from [scan ](https://github.com/JanssenProject/jans/blob/main/jans-linux-setup/jans_setup/scan/static/extension/update_token/UpdateToken.py)folder the token update script.

### LINKED ISSUE #1858: fix: build: sync scan_update_token script #1820 -autocreated
This issue was created because no open issues were referenced in your PR (#1857).

### LINKED ISSUE #1859: fix: build: sync scan_update_token script #1820 -autocreated
This issue was created because no open issues were referenced in your PR (#1857).

### PR DESCRIPTION
**Pull request by iromli**
### Prepare

- [x] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [x] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

#### Target issue

Closes #1820 

#### Implementation Details

Synchronize templates from `jans-linux-setup` to `docker-jans-persistence-loader` image

-------------------
### Test and Document the changes
- [ ] Static code analysis has been run locally and issues have been fixed
- [ ] Relevant unit and integration tests have been added/updated
- [ ] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

Closes #1858, 
Closes #1859,

### CODE REVIEW

**Comment by mo-auto** [comment]
Error: Hi @iromli, You did not reference an open issue in your [PR](1857). I attempted to create an [issue](#1858) for you.    
 Please update that [issues'](#1858) title and body and make sure I correctly referenced it in the above PRs body.

**Comment by iromli** [comment]
@moabu we may need to tweak the workflow to allow referencing closed GH issue from PullRequest title and/or body.

**Comment by mo-auto** [comment]
Error: Hi @iromli, You did not reference an open issue in your [PR](1857). I attempted to create an [issue](#1859) for you.    
 Please update that [issues'](#1859) title and body and make sure I correctly referenced it in the above PRs body.

**Comment by moabu** [comment]
@iromli you can reference a closed  or resolved issue . You just have to mention the right GitHub keywords such as Closes, Resolves ..etc

**Review by moabu — APPROVED** [review]

**Comment by iromli** [comment]
> @iromli you can reference a closed or resolved issue . You just have to mention the right GitHub keywords such as Closes, Resolves ..etc

Noted, thanks.

**Pull request merged**
