### PR TITLE
chore: upgrade css libraries in jans-auth-server #7835

### LINKED ISSUE #7835: chore: upgrade javascript libraries to newer versions in HTML files
Upgrade and remove JavaScript libraries as per [this](https://github.com/JanssenProject/jans/discussions/7117#discussioncomment-7947589) discussion.

### PR DESCRIPTION
**Pull request by jv18creator**
### Prepare

- [ ] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [ ] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

#### Target issue
  
  
  
  
closes #7835

#### Implementation Details
Libraries replaced
- fontawesome v5.8.2 => v6.5.1
- bootstrap v4.0.0 => v5.3.3

Libraries removed
- jquery-ui v1.12.1

-------------------
### Test and Document the changes
- [ ] Static code analysis has been run locally and issues have been fixed
- [ ] Relevant unit and integration tests have been added/updated
- [ ] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

### CODE REVIEW

**Comment by ossdhaval** [comment]
Plus, You'll have to make the same changes for Casa pages as well. I think they are not using these libraries from the same location.

**Comment by jv18creator** [comment]
> Plus, You'll have to make the same changes for Casa pages as well. I think they are not using these libraries from the same location.

Okay @ossdhaval I will check casa codebase and try to do the same.

**Comment by ossdhaval** [comment]
@jv18creator I am in favor of merging this PR now unless you are planning to add more commits.

**Comment by jv18creator** [comment]
> @jv18creator I am in favor of merging this PR now unless you are planning to add more commits.

yes please continue

**Review by yuriyz — APPROVED** [review]

**Comment by jgomer2001** [comment]
was this tested?

**Comment by ossdhaval** [comment]
> was this tested?

Hi @jgomer2001 We tested the pages below with these changes:

- Device auth
- password login
- authorization page

Casa remains to be tested. We planned to test Casa using the nightly build after the PR is merged.

**Review by jgomer2001 — APPROVED** [review]

**Comment by jgomer2001** [comment]
Merged now @ossdhaval @jv18creator

**Pull request merged**
