### PR TITLE
feat(docker-jans-monolith): add docker jans monolith

### LINKED ISSUE #2322: feat: add a monolithic docker image for janssen
For testing and developing purposes add a monolithic janssen docker image can help improve the speed and efficiency of testing and developing.

Specs:
- This image is not for production use ever
- This image should use the linux setup
- Preferably using Ubuntu as the base image

### PR DESCRIPTION
**Pull request by moabu**
### Prepare

- [x] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [x] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

#### Target issue
  
  
  
  
closes #2322

#### Implementation Details
  
- [x] Monolithic image for janssen server
- [x] Uses Ubuntu 20.04
- [x] Uses the linux setup installer
- [x] Includes a docker compose file  
-------------------
### Test and Document the changes
- [ ] Static code analysis has been run locally and issues have been fixed
- [ ] Relevant unit and integration tests have been added/updated
- [ ] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

### CODE REVIEW

**Comment by iromli** [comment]
Got this error while running the entrypoint:

```
/app/scripts/entrypoint.sh: line 64: /opt/dist/scripts/jans-auth: No such file or directory
```

**Comment by moabu** [comment]
> Got this error while running the entrypoint:
> 
> 
> 
> ```
> 
> /app/scripts/entrypoint.sh: line 64: /opt/dist/scripts/jans-auth: No such file or directory
> 
> ```

That shouldn't happen unless the setup didn't execute and there was an error the setup . Likely an error in the Linux installer or snapshot wars .

**Comment by iromli** [comment]
If docker-compose is the preferred way to run the images, i think we should make entrypoint a little bit smarter in installation process (because installation takes a while).

Proposed entrypoint:
1. run `install.py` only if Janssen is not installed
2. a successful installation should create a flag file, i.e. `/deploy`
3. re-running entrypoint (via docker restart or similar command) should check whether flag file is exist or not; it it does, skip installation

**Comment by moabu** [comment]
1. I think we should keep it simple . I guess we can separate the installation script but checking if the installation has been done can be done directly in the entrypoint.sh and just run the installs function if it's needed
2. Agreed
3. Agreed

**Review by iromli — DISMISSED** [review]

**Pull request merged**
