### PR TITLE
fix(jans-config-api): fixed due to couchbase clustter change

### LINKED ISSUE #1867: fix: fix(jans-config-api): fixed due to couchbase clustter change -autocreated
This issue was created because no open issues were referenced in your PR (#1863).

### PR DESCRIPTION
**Pull request by pujavs**
### Prepare

- [x] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [x] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

### Description
Fixed config-api build issue

#### Target issue
  Closes: [1862](https://github.com/JanssenProject/jans/issues/1862)

#### Implementation Details
In config-api `CouchbaseConfigurationResource` `DefaultCouchbaseEnvironment` became obsolete due to orm changes for clustered environment and hence replaced `com.couchbase.client.java.env.DefaultCouchbaseEnvironment` with `com.couchbase.client.java.env.ClusterEnvironment`
-------------------
### Test and Document the changes
- [x] Static code analysis has been run locally and issues have been fixed
- [ ] Relevant unit and integration tests have been added/updated
- [ ] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

Closes #1867,

### CODE REVIEW

**Comment by mo-auto** [comment]
Error: Hi @pujavs, You did not reference an open issue in your [PR](1863). I attempted to create an [issue](#1864) for you.    
 Please update that [issues'](#1864) title and body and make sure I correctly referenced it in the above PRs body.

**Comment by mo-auto** [comment]
Error: Hi @pujavs, You did not reference an open issue in your [PR](1863). I attempted to create an [issue](#1865) for you.    
 Please update that [issues'](#1865) title and body and make sure I correctly referenced it in the above PRs body.

**Comment by mo-auto** [comment]
Error: Hi @pujavs, You did not reference an open issue in your [PR](1863). I attempted to create an [issue](#1866) for you.    
 Please update that [issues'](#1866) title and body and make sure I correctly referenced it in the above PRs body.

**Comment by mo-auto** [comment]
Error: Hi @pujavs, You did not reference an open issue in your [PR](1863). I attempted to create an [issue](#1867) for you.    
 Please update that [issues'](#1867) title and body and make sure I correctly referenced it in the above PRs body.

**Review by yuriyz — APPROVED** [review]

**Pull request merged**
