### PR TITLE
feat: initial commit jans-tarp

### LINKED ISSUE #4822: fix: feat: initial commit jans-tarp -autocreated
`jans-tarp` is chrome extension for relying party useful for testing authentication flows.
This issue was created because no open issues were referenced in your PR (#4820).

### PR DESCRIPTION
**Pull request by duttarnab**
initial commit jans-tarp
Closes #4822,

### CODE REVIEW

**Comment by mo-auto** [comment]
Error: Hi @duttarnab, You did not reference an open issue in your [PR](4820). I attempted to create an [issue](#4822) for you.    
 Please update that [issues'](#4822) title and body and make sure I correctly referenced it in the above PRs body.

**Review by christian-hawk — CHANGES_REQUESTED** [review]
@duttarnab thanks for the PR. Why are you adding files to `jans-tent` in your initial commit?
Also, as warned by @moabu we should **not** commit certs/keys to the repo.

**Comment by duttarnab** [comment]
Hi @christian-hawk 
I am adding a new project called `jans-tarp` in `demos/`  directory. I think I am not pushing any keys.

**Review by christian-hawk — DISMISSED** [review]
All good from my side.

**Comment by christian-hawk** [comment]
@moabu may you please check/merge?

**Review by moabu — APPROVED** [review]

**Pull request merged**
