### PR TITLE
docs(passport-js): social logins auth using passport-js

### LINKED ISSUE #1960: docs(passport-js): social logins auth using passport-js
This issue was created because no open issues were referenced in your PR (#1959).

### PR DESCRIPTION
**Pull request by kdhttps**
Documentation for social logins authentication integration using passport-js
Closes #1960,

### CODE REVIEW

**Comment by mo-auto** [comment]
Error: Hi @kdhttps, You did not reference an open issue in your [PR](1959). I attempted to create an [issue](#1960) for you.    
 Please update that [issues'](#1960) title and body and make sure I correctly referenced it in the above PRs body.

**Review by maduvena — CHANGES_REQUESTED** [review]
fix the doc as per feedback

**Review by maduvena — APPROVED** [review]

**Comment by kdhttps** [comment]
"Merging is blocked" for us.  anyone please merge this PR?

**Comment by kdhttps** [comment]
thanks, @shmorri , please review again changes

**Review by shmorri — APPROVED** [review]

**Pull request merged**
