### PR TITLE
Refresh links and sections in Jans README

### LINKED ISSUE #2351: fix: refresh jans README.md
**Describe the bug**
On [README.md](https://github.com/JanssenProject/jans/blob/main/README.md) some of the links are not working and the content in some of the sections is outdated. 

##### Updates needed:
- quick start link is 404
- User guides link is 404
- contribution guide link should go to the page on `docs.jans.io`
- community docs link is 404
- Developer guides link should go to the page on `docs.jans.io`
- license badge isn't pointing to the license page
- contributors badge isn't pointing to the contributors list
- installation section: link should now point to official docs
- code of conduct : link should now point to official docs
- contribution guide : link should now point to official docs
- Documentation : link should now point to official docs
- Governance : charter link is 404. link should now point to official docs
- Support : change the description with respect to documentation

### PR DESCRIPTION
**Pull request by ossdhaval**
### Prepare

- [x] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [x] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

#### Target issue
  
  
  
  
closes #2351 

#### Implementation Details
- [x] User guides link is 404
- [x] contribution guide link should go to the page on docs.jans.io
- [x] community docs link is 404
- [x] Developer guides link should go to the page on docs.jans.io
- [x] license badge isn't pointing to the license page
- [x] contributors badge isn't pointing to the contributors list
- [x] installation section: link should now point to official docs
- [x] code of conduct : link should now point to official docs
- [x] contribution guide : link should now point to official docs
- [x] Documentation : link should now point to official docs
- [x] Governance : charter link is 404. link should now point to official docs
- [x] Support : change the description with respect to documentation

-------------------
### Test and Document the changes
- [ ] Static code analysis has been run locally and issues have been fixed `NA`
- [ ] Relevant unit and integration tests have been added/updated `NA`
- [x] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

### CODE REVIEW

**Comment by ossdhaval** [comment]
About the `quick start link is 404`:

This link is currently 404 because we removed the section from README long back. We can either choose to drop the link from README or create content for it. In my view, we should keep it and develop content for `quick start` as it will help increase adoption by easing the entry. 

@nynymike @moabu @shmorri 
If you think there is a relevant section in our current documentation outline, then please suggest. We can point this link to that section. 
If we need to create new content, see the screenshot below. It is from an old version of README(around March) and it describes what we wanted to have in the `Quick Start` section.

image

@moabu 
It was not possible to create this kind of setup at that time, but do you think this is possible now?

**Comment by ossdhaval** [comment]
@nynymike @moabu @shmorri Can you please share your thoughts about the `quick start` section.

**Review by moabu — APPROVED** [review]

**Comment by moabu** [comment]
> About the `quick start link is 404`:
> 
> This link is currently 404 because we removed the section from README long back. We can either choose to drop the link from README or create content for it. In my view, we should keep it and develop content for `quick start` as it will help increase adoption by easing the entry.
> 
> @nynymike @moabu @shmorri If you think there is a relevant section in our current documentation outline, then please suggest. We can point this link to that section. If we need to create new content, see the screenshot below. It is from an old version of README(around March) and it describes what we wanted to have in the `Quick Start` section.
> 
> image
> 
> @moabu It was not possible to create this kind of setup at that time, but do you think this is possible now?

yes, the content now exists creating a full deployment in docker here 
https://github.com/JanssenProject/jans/tree/main/docker-jans-monolith

**Comment by ossdhaval** [comment]
As discussed with @moabu, I'll create a new quick-start guide on the docs site. That will be a separate PR. I'll remove quick-start task from this PR and merge it.

**Pull request merged**
