### PR TITLE
docs: workspace setup

### PR DESCRIPTION
**Pull request by ossdhaval**
### Prepare

- [x] Read contribution guidelines
- [x] Read license information

-------------------

#### Target issue #
Jans currently doesn't have a step-by-step guide for developers on how to setup, run, debug and execute integration tests from an IDE. This guide enables community to easily setup a working environment where they can make code changes and run integration tests as well before pushing their contributions to GH repo.  

Once complete, this guide will be linked to CONTRIBUTING.md

#### Implementation Details
The guide is split into three documents
1. **Workspace setup guide**: Get code, setup Jetty, setup MySQL, Build and deploy Jans from IDE on local Jetty
2. **Test setup guide**: Setup test profiles and run tests from IDE
3. **Debug guide**: How to launch and debug Jans server from within IDE

#### Open item :red_circle: 

- DB load script:
  Once the developer installs MySQL on local system, the DB needs to be populated with seed data. Preferably with test data as well. We don't have SQL script that developers can run and populate DB. In discussion with @yurem, it seemed that the best way to do this would be to take dump from the DB of an installed system and run it against the local DB. 
  
  The generation of this script needs to be automated. One way to do this is to create this data dump script after every successful installation on Jenkins integration servers. Once this script is generated, it has to be made available via a link (hosted on servers or stored in GH repo). Similar mechanism has be to established for other persistence types. 
  **Need comments and suggestions on this.**

### CODE REVIEW

**Review by nynymike — APPROVED** [review]
A step in the right direction.

**Review by moabu — APPROVED** [review]

**Comment by ossdhaval** [comment]
Moving this to draft as we still need to figure out how to seed data into DB before going live.

**Comment by moabu** [comment]
@mbaser I think we can make the `jans-linux-setup` take in an operation to seed data without provisioning services. Meaning have the user pass in the database type and connection params and load automatic test data to help with development testing.

**Comment by moabu** [comment]
Adding the issue in regards of seeding data 
https://github.com/JanssenProject/jans/issues/1155

**Comment by ossdhaval** [comment]
This work may still be required as the thought process is same and everyone agrees that we need this. But closing this PR for now as it has taken less priority since long time.

**Pull request closed without merging**
