### PR TITLE
feat(jans-config-api): agama flow endpoint

### LINKED ISSUE #1904: fix: feat(jans-config-api): agama flow endpoint -autocreated
This issue was created because no open issues were referenced in your PR (#1898).

### PR DESCRIPTION
**Pull request by pujavs**
### Prepare

- [x] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [x] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

### Description
New service for agama flows to fetch, create, update and delete agama flows

#### Target issue
closes #[1509](https://github.com/JanssenProject/jans/issues/1509)

#### Implementation Details
**Agama endpont:**
1) /jans-config-api/api/v1/agama
     GET - Fetches all the flow
     POST - Create a new flow

2) /jans-config-api/api/v1/agama/{qname}
    GET - Fetch flow based on qname
    POST - Create a flow with request payload reading source file
    PUT - Updates a flow based on qname
    DELETE - Deletes a flow

**Agama:**  [ProtoFlow.java](http://protoflow.java/) is modified to change field name from `QName` to `qname` 
And related change in agama code for the same
**Setup:** Changes to jans-config-api config template to add agama related config properties.

-------------------
### Test and Document the changes
- [x] Static code analysis has been run locally and issues have been fixed
- [x] Relevant unit and integration tests have been added/updated
- [x] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

Closes #1904,

### CODE REVIEW

**Comment by mo-auto** [comment]
Error: Hi @pujavs, You did not reference an open issue in your [PR](1898). I attempted to create an [issue](#1899) for you.    
 Please update that [issues'](#1899) title and body and make sure I correctly referenced it in the above PRs body.

**Comment by mo-auto** [comment]
Error: Hi @pujavs, You did not reference an open issue in your [PR](1898). I attempted to create an [issue](#1900) for you.    
 Please update that [issues'](#1900) title and body and make sure I correctly referenced it in the above PRs body.

**Comment by mo-auto** [comment]
Error: Hi @pujavs, You did not reference an open issue in your [PR](1898). I attempted to create an [issue](#1901) for you.    
 Please update that [issues'](#1901) title and body and make sure I correctly referenced it in the above PRs body.

**Comment by mo-auto** [comment]
Error: Hi @pujavs, You did not reference an open issue in your [PR](1898). I attempted to create an [issue](#1902) for you.    
 Please update that [issues'](#1902) title and body and make sure I correctly referenced it in the above PRs body.

**Comment by mo-auto** [comment]
Error: Hi @pujavs, You did not reference an open issue in your [PR](1898). I attempted to create an [issue](#1903) for you.    
 Please update that [issues'](#1903) title and body and make sure I correctly referenced it in the above PRs body.

**Comment by mo-auto** [comment]
Error: Hi @pujavs, You did not reference an open issue in your [PR](1898). I attempted to create an [issue](#1904) for you.    
 Please update that [issues'](#1904) title and body and make sure I correctly referenced it in the above PRs body.

**Comment by pujavs** [comment]
@yuriyz, @jgomer2001 and @devrimyatar  request you to please review and approve the changes related to agama endpoint.

**Review by yuriyz — APPROVED** [review]

**Review by jgomer2001 — APPROVED** [review]

**Pull request merged**
