### PR TITLE
feat: add feature to include custom-claims in user-info endpoint of admin-ui plugin #2969

### LINKED ISSUE #2969: feat(jans-config-api) : add feature to include custom-claims in user-info endpoint of admin-ui plugin
The claims added to the session in the authentication script should be fetched in the user-info endpoint of the admin-ui plugin.

This is especially useful when we need to add some claims from the InBound custom script to jans user-info endpoint response.

- [x] create GitHub Inbound custom script. The script will also add GitHub username and access_token in the session.
- [x] create a GitHub Introspection script to add GitHub claims from the session to the Introspection response. 
- [x] In the admin-ui plugin add the GitHub claims in the user-info response.

### PR DESCRIPTION
**Pull request by duttarnab**
The claims added to the session in the authentication script should be fetched in the user-info endpoint of the admin-ui plugin.

This is especially useful when we need to add some claims from the InBound custom script to jans user-info endpoint response.

- [x] create GitHub Inbound custom script. The script will also add GitHub username and access_token in the session.
- [x] create a GitHub Introspection script to add GitHub claims from the session to the Introspection response. 
- [x] In the admin-ui plugin add the GitHub claims in the user-info response.

closes #2969

### CODE REVIEW

**Comment by devrimyatar** [comment]
@duttarnab Please move scripts to `docs/script-catalog/introspection`

**Comment by duttarnab** [comment]
I have moved the script to docs/script-catalog/ directory.

**Review by devrimyatar — CHANGES_REQUESTED** [review]
Script placeholders seems not correct. Please follow this guide https://github.com/JanssenProject/jans/pull/2999#pullrequestreview-1181211769

**Comment by duttarnab** [comment]
> Script placeholders seems not correct. Please follow this guide https://github.com/JanssenProject/jans/pull/2999#pullrequestreview-1181211769

Fixed

**Review by devrimyatar — APPROVED** [review]

**Review by yuriyz — APPROVED** [review]

**Review by moabu — APPROVED** [review]

**Pull request merged**
