### PR TITLE
refactor(docs): refactor interception script documentation

### PR DESCRIPTION
**Pull request by mmrraju**
### Prepare

- [x] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [x] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

### Description
This PR refactors script documentation by moving all files under `docs/admin/developer/scripts` to a new folder `docs/script-catalog`.

This change was made to:
- Improve clarity in locating script-related documentation.
- Create a more logical and centralized documentation structure.

#### Target issue
  
  https://github.com/JanssenProject/jans/issues/5924
  
  
closes #issue-number-here

#### Implementation Details
  

-------------------
### Test and Document the changes
- [ ] Static code analysis has been run locally and issues have been fixed
- [ ] Relevant unit and integration tests have been added/updated
- [ ] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

Please check the below before submitting your PR. The PR will not be merged if there are no commits that start with `docs:` to indicate documentation changes or if the below checklist is not selected.
- [x] **I confirm that there is no impact on the docs due to the code changes in this PR.**

### CODE REVIEW

**Comment by ossdhaval** [comment]
@mmrraju Does this complete movement of all the files from under the `developer/scripts` to `script-catalog`? There are 33 files at the source.

**Comment by mmrraju** [comment]
@ossdhaval  Yes, some were duplicates, so I removed them. Additionally, I added new files, which we may update later.

Let me check if I can remove the scripts in the same PR. Otherwise, I will need to create a new PR.

**Review by mzico — APPROVED** [review]

**Review by ossdhaval — DISMISSED** [review]

**Comment by ossdhaval** [comment]
@mmrraju also check all the references to the scripts in the code and docs. Update to refer to new locations of the scripts.

**Comment by mmrraju** [comment]
closing this PR there was DCO issue. new [PR](https://github.com/JanssenProject/jans/pull/9753)

**Pull request closed without merging**
