### PR TITLE
docs: moved content from jans.io

### PR DESCRIPTION
**Pull request by nynymike**
Providing more informative details on README. Also added project logos and community documents (charter, code of conduct).

### CODE REVIEW

**Review by shmorri — DISMISSED** [review]

**Comment by moabu** [comment]
@ossdhaval can you work on this PR please. The commits are unsigned and we should move these *.md in one folder `docs`. A folder in the main repo means project and here we can consolidate those together to follow a better standard. Please take a look at https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors.

**Comment by ossdhaval** [comment]
I am restructuring the remaining repos. Below is what I propose to be target state:

`jans` : is our monorepo
`jans` -> `docs` : will hold all Janssen documentation. `docs` is a separate repo right now, and will be archived.
`jans` -> `docs` -> `community` -> will hold all community related content. Currently this is under `home` repo

`.github` -> repo should be archived and content should be placed under `jans` appropriately
`docs` -> repo should be archived
`home` -> repo should be archived.

Does it sound alright?

**Comment by moabu** [comment]
Yes sounds right.

**Comment by ossdhaval** [comment]
> @nynymike @moabu @shmorri
> 
> Below is what I propose for restructuring of remaining 4 repos:
> 
> `jans` : is our monorepo `jans` -> `docs` : will hold all Janssen documentation. `docs` is a separate repo right now, and will be archived. `jans` -> `docs` -> `community` -> will hold all community related content. Currently this is under `home` repo
> 
> `.github` -> repo should be archived and contents should be placed under `jans` appropriately `docs` -> repo should be archived `home` -> repo should be archived.
> 
> Does it sound alright?

I'll open a new PR for these changes as logically separate change. This PR can be merged and closed.

@shmorri I have enabled auto-merge for this PR. With your approval, it'll get merged.

**Review by shmorri — APPROVED** [review]

**Comment by shmorri** [comment]
Changes merged in PR https://github.com/JanssenProject/jans/pull/707

**Pull request closed without merging**
