### PR TITLE
Update README.md

### LINKED ISSUE #4559: fix: Update README.md -autocreated
This issue was created because no open issues were referenced in your PR (#4558).

### PR DESCRIPTION
**Pull request by manojs1978**
virtual env created with python3 so need to run main.py with python3

### Prepare

- [ ] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [ ] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

#### Target issue
  
  
  
  
closes #4559

#### Implementation Details
  

-------------------
### Test and Document the changes
- [ ] Static code analysis has been run locally and issues have been fixed
- [ ] Relevant unit and integration tests have been added/updated
- [ ] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

Closes #4559,

### CODE REVIEW

**Comment by mo-auto** [comment]
Error: Hi @manojs1978, You did not reference an open issue in your [PR](4558). I attempted to create an [issue](#4559) for you.    
 Please update that [issues'](#4559) title and body and make sure I correctly referenced it in the above PRs body.

**Comment by christian-hawk** [comment]
virtual env created with python3 so need to run main.py with python3

@manojs1978 why do you say that? that's not true, as far as I know.

**Review by christian-hawk — COMMENTED** [review]
`python main.py` should be used in any condition, as long as you are inside venv.

**Comment by manojs1978** [comment]
> `python main.py` should be used in any condition, as long as you are inside venv.

hi @christian-hawk ,
ok got it,
Thanks
we can close this now

**Pull request closed without merging**
